# Generated by Django 5.2.7 on 2025-11-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_characterclass_race_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterclass',
            options={'ordering': ['name'], 'verbose_name': 'Character Class', 'verbose_name_plural': 'Character Classes'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name'], 'verbose_name': 'Race', 'verbose_name_plural': 'Races'},
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_characters', to='users.characterclass', verbose_name='Chosen class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='race_characters', to='users.race', verbose_name='Chosen race'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='User related to character'),
        ),
    ]
