# Generated by Django 5.2.7 on 2025-11-27 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_characterclass_options_alter_race_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Health points'),
        ),
        migrations.AddField(
            model_name='character',
            name='mp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mana points'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Skill points'),
        ),
    ]
