# Generated by Django 5.2.7 on 2025-11-20 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_characterclass_race_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type name')),
                ('category', models.CharField(max_length=50, verbose_name='Category(sport, leasure, work...)')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon name (lucide-react)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration in minutes')),
                ('calories', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Calories burned')),
                ('satisfaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Satisfaction level')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Optional comentary')),
                ('xp_earned', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Experience earned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.character', verbose_name='Associated character')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='tracking.activitytype', verbose_name='Activity type')),
            ],
        ),
    ]
