# Generated by Django 6.0.1 on 2026-01-07 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration in minutes')),
                ('calories', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Calories burned')),
                ('satisfaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Satisfaction level')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Optional commentary')),
                ('xp_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Experience earned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type name')),
                ('category', models.CharField(max_length=50, verbose_name='Category(sport, leasure, work...)')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon name (lucide-react)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Activity type',
                'verbose_name_plural': 'Activity types',
                'ordering': ['category', 'name'],
            },
        ),
    ]
