# Generated by Django 6.0.1 on 2026-01-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.character', verbose_name='Associated character'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to='tracking.activitytype', verbose_name='Activity type'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['character', '-created_at'], name='tracking_ac_charact_b497a1_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', '-created_at'], name='tracking_ac_activit_c98c71_idx'),
        ),
    ]
