# Generated by Django 5.2.7 on 2025-11-24 11:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('users', '0003_alter_characterclass_options_alter_race_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Activity type', 'verbose_name_plural': 'Activity types'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to='tracking.activitytype', verbose_name='Activity type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Calories burned'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Optional commentary'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['character', '-created_at'], name='tracking_ac_charact_b497a1_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', '-created_at'], name='tracking_ac_activit_c98c71_idx'),
        ),
    ]
