# Generated by Django 5.2.7 on 2025-11-25 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_activity_options_alter_activitytype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='xp_earned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Experience earned'),
        ),
    ]
