# Generated by Django 5.2.7 on 2025-11-24 11:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_characterclass_options_alter_race_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Equipment name')),
                ('description', models.TextField(verbose_name='Equipment description and lore')),
                ('slot', models.CharField(max_length=20, verbose_name='Equipment type (weapon, relic, outfit)')),
                ('rarity', models.CharField(max_length=20, verbose_name='Equipment rariry (common, rare, legendary)')),
                ('primary_stat_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bonus type (xp bonus, narrative perk, combat bonus)')),
                ('primary_stat_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bonus value')),
                ('secondary_stat_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Second bonus type (xp bonus, narrative perk, combat bonus)')),
                ('secondary_stat_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Second bonus value')),
                ('tertiary_stat_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Third bonus type (xp bonus, narrative perk, combat bonus)')),
                ('tertiary_stat_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Third bonus value')),
                ('required_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Level required wear the equipment')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('required_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='users.characterclass', verbose_name='Required class (NULL = all classes)')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'ordering': ['rarity', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill name')),
                ('description', models.TextField(verbose_name='Skill description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active (usable) vs Passive')),
                ('is_npc_skill', models.BooleanField(default=False, verbose_name='Skills available only to NPCs')),
                ('unlock_at_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Required level to unlock')),
                ('bonus_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bonus type (combat, dialog, environment...)')),
                ('bonus_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bonus value')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.characterclass', verbose_name='Required class')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['character_class', 'unlock_at_level'],
            },
        ),
        migrations.CreateModel(
            name='CharacterEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equiped', models.BooleanField(default=False, verbose_name='Currently equipped or not')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Acquisition date')),
                ('acquired_from', models.CharField(max_length=50, verbose_name='Source (level_up, adventure...)')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_equipments', to='users.character', verbose_name='Character')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='game.equipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Équipement du personnage',
                'verbose_name_plural': 'Équipements des personnages',
                'ordering': ['acquired_at'],
                'unique_together': {('character', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Acquisition date')),
                ('acquired_level', models.IntegerField(verbose_name='Level at acquisition time')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquired_skills', to='users.character', verbose_name='Associated character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='game.skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Character skill',
                'verbose_name_plural': 'Character skills',
                'ordering': ['acquired_level', 'skill__unlock_at_level'],
                'unique_together': {('character', 'skill')},
            },
        ),
    ]
