# Generated by Django 6.0.1 on 2026-01-07 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False, verbose_name='Is currently equipped')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Acquisition date')),
                ('acquired_from', models.CharField(max_length=50, verbose_name='Source (level_up, adventure...)')),
            ],
            options={
                'verbose_name': 'Character equipment',
                'verbose_name_plural': 'Characters equipments',
                'ordering': ['acquired_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Acquisition date')),
                ('acquired_level', models.IntegerField(default=0, verbose_name='Level at acquisition time')),
            ],
            options={
                'verbose_name': 'Character skill',
                'verbose_name_plural': 'Character skills',
                'ordering': ['acquired_level', 'skill__unlock_at_level'],
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Enemy name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Health points')),
                ('min_damage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum damages')),
                ('max_damage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum damages')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Is boss ?')),
                ('xp_reward', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='XP reward')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Enemy',
                'verbose_name_plural': 'Enemies',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Equipment name')),
                ('description', models.TextField(verbose_name='Equipment description and lore')),
                ('slot', models.CharField(max_length=20, verbose_name='Equipment type (weapon, relic, outfit)')),
                ('rarity', models.CharField(max_length=20, verbose_name='Equipment rariry (common, rare, legendary)')),
                ('primary_stat_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bonus type (xp bonus, narrative perk, combat bonus)')),
                ('primary_stat_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bonus value')),
                ('secondary_stat_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Second bonus type (xp bonus, narrative perk, combat bonus)')),
                ('secondary_stat_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Second bonus value')),
                ('tertiary_stat_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Third bonus type (xp bonus, narrative perk, combat bonus)')),
                ('tertiary_stat_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Third bonus value')),
                ('required_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Level required wear the equipment')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'ordering': ['rarity', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill name')),
                ('description', models.TextField(verbose_name='Skill description')),
                ('skill_type', models.CharField(choices=[('combat', 'Combat'), ('env', 'Environment'), ('social', 'Social'), ('craft', 'Craft'), ('mystical', 'Mystical'), ('utility', 'Utility')], default='combat', max_length=10, verbose_name='Skill type')),
                ('cooldown', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Skill cooldown (in game turn)')),
                ('is_active', models.BooleanField(default=False, verbose_name='active skills (contraty to a passive)')),
                ('is_npc_skill', models.BooleanField(default=False, verbose_name='Skills available only to NPCs')),
                ('unlock_at_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Required level to unlock')),
                ('bonus_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Skill type (combat, dialog, environment...)')),
                ('bonus_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Numerical value if needed (damages, skill bonus...)')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['character_class', 'unlock_at_level'],
            },
        ),
    ]
