# Generated by Django 5.2.7 on 2025-11-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterequipment',
            name='is_equiped',
        ),
        migrations.AddField(
            model_name='characterequipment',
            name='is_equipped',
            field=models.BooleanField(default=False, verbose_name='Is currently equipped'),
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='acquired_level',
            field=models.IntegerField(default=0, verbose_name='Level at acquisition time'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skill type (combat, dialog, environment...)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='bonus_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Numerical value if needed (damages, skill bonus...)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active skills (contraty to a passive)'),
        ),
    ]
