# Generated by Django 6.0.1 on 2026-01-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0002_initial'),
        ('game', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterequipment',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_equipments', to='users.character', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquired_skills', to='users.character', verbose_name='Associated character'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventures.reward', verbose_name='Rewards'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='required_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='users.characterclass', verbose_name='Required class (NULL = all classes)'),
        ),
        migrations.AddField(
            model_name='characterequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='game.equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='skill',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.characterclass', verbose_name='Required class'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='enemies', to='game.skill', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='game.skill', verbose_name='Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='characterequipment',
            unique_together={('character', 'equipment')},
        ),
        migrations.AlterUniqueTogether(
            name='characterskill',
            unique_together={('character', 'skill')},
        ),
    ]
