# Generated by Django 5.2.7 on 2025-11-26 16:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
        ('game', '0002_remove_characterequipment_is_equiped_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterequipment',
            options={'ordering': ['acquired_at'], 'verbose_name': 'Character equipment', 'verbose_name_plural': 'Characters equipments'},
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Enemy name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Health points')),
                ('min_damage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum damages')),
                ('max_damage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum damages')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Is boss ?')),
                ('xp_reward', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='XP reward')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventures.reward', verbose_name='Rewards')),
                ('skills', models.ManyToManyField(blank=True, null=True, related_name='enemies', to='game.skill', verbose_name='Skills')),
            ],
            options={
                'verbose_name': 'Enemy',
                'verbose_name_plural': 'Enemies',
            },
        ),
    ]
