# Generated by Django 5.2.7 on 2025-11-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_characterequipment_options_enemy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='enemies', to='game.skill', verbose_name='Skills'),
        ),
    ]
