# Generated by Django 5.2.7 on 2025-11-26 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_enemy_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='max_damage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(999)], verbose_name='Maximum damages'),
        ),
    ]
