# Generated by Django 5.2.7 on 2025-11-26 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_enemy_max_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='max_damage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum damages'),
        ),
    ]
