# Generated by Django 5.2.7 on 2025-11-27 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_enemy_max_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='cooldown',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Skill cooldown (in game turn)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('combat', 'Combat'), ('env', 'Environment'), ('social', 'Social'), ('craft', 'Craft'), ('mystical', 'Mystical'), ('utility', 'Utility')], default='combat', max_length=10, verbose_name='Skill type'),
        ),
    ]
