# Generated by Django 5.2.7 on 2025-11-27 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_skill_cooldown_skill_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='cooldown',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Skill cooldown (in game turn)'),
        ),
    ]
