# Generated by Django 6.0.1 on 2026-01-07 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Adventure title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Adventure synopsis')),
                ('min_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Level required')),
                ('base_xp_reward', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Experience rewarded for completion')),
                ('difficulty', models.CharField(max_length=20, verbose_name='Difficulty (easy, medium, hard, legendary)')),
                ('estimated_duration', models.IntegerField(blank=True, null=True, verbose_name='Estimated duration in minutes')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish adventure')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
            options={
                'verbose_name': 'Aventure',
                'verbose_name_plural': 'Aventures',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('xp', 'Experience Points'), ('item', 'Item'), ('skill', 'Skill'), ('currency', 'Currency')], max_length=10, verbose_name='Reward type')),
                ('value', models.IntegerField(verbose_name='Value (XP amount, item ID, etc.)')),
                ('description', models.CharField(max_length=200, verbose_name='Reward description')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Order in adventure')),
                ('title', models.CharField(max_length=200, verbose_name='Scene title')),
                ('content', models.TextField(verbose_name='Narrative text')),
                ('is_starting_scene', models.BooleanField(default=False, verbose_name='Is opening scene')),
                ('is_ending_scene', models.BooleanField(default=False, verbose_name='Is ending scene')),
                ('is_fight_scene', models.BooleanField(default=False, verbose_name='Is combat scene')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Scene',
                'verbose_name_plural': 'Scenes',
                'ordering': ['scene_order'],
            },
        ),
        migrations.CreateModel(
            name='SceneChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Choice text')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Display order')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is the choice available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Scene choice',
                'verbose_name_plural': 'Scene choices',
                'ordering': ['scene', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AdventureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed adventure')),
                ('xp_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total xp earned')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completion date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='adventures.adventure', verbose_name='Adventure')),
            ],
        ),
    ]
