# Generated by Django 6.0.1 on 2026-01-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
        ('game', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureprogress',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_progressions', to='users.character', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='reward',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.equipment', verbose_name='Item reward (if type=item)'),
        ),
        migrations.AddField(
            model_name='reward',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.skill', verbose_name='Skill reward (if type=skill)'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='rewards',
            field=models.ManyToManyField(blank=True, related_name='adventures', to='adventures.reward', verbose_name='Rewards for completing the adventure'),
        ),
        migrations.AddField(
            model_name='scene',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='adventures.adventure', verbose_name='Parent adventure'),
        ),
        migrations.AddField(
            model_name='scene',
            name='enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.enemy', verbose_name='Enemy (if fight scene)'),
        ),
        migrations.AddField(
            model_name='scene',
            name='next_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_scenes', to='adventures.scene', verbose_name='Next scene (if no choice)'),
        ),
        migrations.AddField(
            model_name='scene',
            name='previous_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_scenes', to='adventures.scene', verbose_name='Previous scene'),
        ),
        migrations.AddField(
            model_name='adventureprogress',
            name='current_scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressed_scenes', to='adventures.scene', verbose_name='Current scene'),
        ),
        migrations.AddField(
            model_name='scenechoice',
            name='next_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices_leading_here', to='adventures.scene', verbose_name='Next scene to play'),
        ),
        migrations.AddField(
            model_name='scenechoice',
            name='required_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_class_for_choices', to='users.characterclass', verbose_name='Required class for choice'),
        ),
        migrations.AddField(
            model_name='scenechoice',
            name='required_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_equipment_for_choices', to='game.equipment', verbose_name='Equipment required'),
        ),
        migrations.AddField(
            model_name='scenechoice',
            name='required_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_skill_for_choices', to='game.skill', verbose_name='Required skill'),
        ),
        migrations.AddField(
            model_name='scenechoice',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='adventures.scene', verbose_name='Parent scene'),
        ),
        migrations.AddConstraint(
            model_name='adventureprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('completed', False)), fields=('character', 'adventure'), name='unique_active_progress_per_character'),
        ),
        migrations.AlterUniqueTogether(
            name='scenechoice',
            unique_together={('scene', 'order')},
        ),
    ]
