# Generated by Django 5.2.7 on 2025-11-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
        ('game', '0003_alter_characterequipment_options_enemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.enemy', verbose_name='Enemy (if fight scene)'),
        ),
        migrations.AddField(
            model_name='scene',
            name='is_fight_scene',
            field=models.BooleanField(default=False, verbose_name='Is combat scene'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publish adventure'),
        ),
    ]
