# Generated by Django 5.2.7 on 2025-11-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_scene_enemy_scene_is_fight_scene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='next_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_scenes', to='adventures.scene', verbose_name='Next scene (if no choice)'),
        ),
    ]
