# Generated by Django 6.0.1 on 2026-01-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenechoice',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('lose_hp', 'HP loss'), ('lose_mp', 'MP loss')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scenechoice',
            name='effect_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
