# Generated by Django 5.2.7 on 2025-11-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_scene_next_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='previous_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_scenes', to='adventures.scene', verbose_name='Previous scene'),
        ),
    ]
